menu:
  Tutorials: /tutorials/
  Docs: /guide/
  API: /api/

  Github: https://github.com/bitpay/bitcore
  Forum: http://labs.bitpay.com/

doc_sidebar:
  Home:
    Get Started: index.html
    Contributing: contributing.html

  Node:
    Get Started: module/node/index.html
    Build: module/node/build.html
    Bus: module/node/bus.html
    Errors: module/node/errors.html
    Node: module/node/node.html
    Patch: module/node/patch.html
    Release: module/node/release.html
    Services: module/node/services.html
    Development: module/node/testing.html

  Node Services:
    Bitcoind: module/node/services/bitcoind.html
    Database: module/node/services/db.html
    Address: module/node/services/address.html
    Web: module/node/services/web.html

  Bitcore:
    Get Started: index.html
    Address: address.html
    Block: block.html
    Browser: browser.html
    Crypto: crypto.html
    Encoding: encoding.html
    HD Keys: hierarchical.html
    Networks: networks.html
    Private Key: privatekey.html
    Public Key: publickey.html
    Script: script.html
    Transaction: transaction.html
    Unit: unit.html
    Unspent Output: unspentoutput.html
    URI: uri.html

  Payment Protocol:
    Usage: module/payment-protocol/index.html

  Mnemonic:
    Overview: module/mnemonic/index.html

  Peer-to-Peer:
    Overview: module/p2p/index.html
    Messages: module/p2p/messages.html
    Peer: module/p2p/peer.html
    Pool: module/p2p/pool.html

  Message Signing and Verification:
    Overview: module/message/index.html

  ECIES:
    Overview: module/ecies/index.html

  Channel:
    Overview: module/channel/index.html

  Explorers:
    Overview: module/explorers/index.html

tutorials_sidebar:
  Tutorials:
    Full Node: fullnode.html
    Payment Processor: payments.html
    Proof-Of-Existence: poe.html

api_sidebar:

  Node:
    Bus: module/node/bus.html
    Node: module/node/node.html
    Transaction: module/node/transaction.html

  Node Services:
    Bitcoind: module/node/services/bitcoind.html
    Database: module/node/services/db.html
    Address: module/node/services/address/index.html
    Address/History: module/node/services/address/history.html
    Web: module/node/services/web.html

  Bitcore:
    Address: address.html
    Block: block/block.html
    BlockHeader: block/blockheader.html
    HDPrivateKey: hdprivatekey.html
    HDPublicKey: hdpublickey.html
    Networks: networks.html
    PrivateKey: privatekey.html
    PublicKey: publickey.html
    Unit: unit.html
    URI: uri.html
    Crypto/Point: crypto/point.html
    Script: script/script.html
    Transaction: transaction/transaction.html
    Transaction/UnspentOutput: transaction/unspentoutput.html
    Transaction/Signing: transaction/sighash.html

  Mnemonic:
    Mnemonic: module/mnemonic/mnemonic.html

  Peer-to-Peer:
    Inventory: module/p2p/inventory.html
    Messages: module/p2p/messages/index.html
    Peer: module/p2p/peer.html
    Pool: module/p2p/pool.html

  Message Signing and Verification:
    Overview: module/message/message.html

  Channel:
    Consumer: module/channel/consumer.html
    Provider: module/channel/provider.html
    Transactions/Commitment: module/channel/transactions/commitment.html
    Transactions/Payment: module/channel/transactions/payment.html
    Transactions/Refund: module/channel/transactions/refund.html

  Explorers:
    Insight: module/explorers/insight.html

google_analytics: UA-24163874-2
twitter: bitpay
github: bitpay/bitcore
